version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
    networks:
      - bike-network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    depends_on:
      - postgres
    ports:
      - "7001:7001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - bike-network

  bike-catalog-service:
    build:
      context: ./bike-catalog
    container_name: bike-catalog-service
    depends_on:
      - postgres
    ports:
      - "7002:7002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bike_catalog_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - bike-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - bike-network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - bike-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka
    networks:
      - bike-network

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    depends_on:
      - postgres
    ports:
      - "7003:7003"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/notifications_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      MAIL_USERNAME: gaddojuc@gmail.com
      MAIL_PASSWORD: XXXXX
      MAIL_HOSTNAME: mailhog
      MAIL_PORT: 1025
    networks:
      - bike-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - bike-network

  bike-lease-ui:
    image: bike-lease-ui
    container_name: bike-lease-ui
    ports:
      - "4200:80"
    networks:
      - bike-network

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command:
      - "-config.file=/etc/tempo.yaml"
    volumes:
      - ./docker/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"
    networks:
      - bike-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    command:
      - "--config=/etc/otel-collector-config.yaml"
    volumes:
      - ./docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"
    depends_on:
      - tempo
    networks:
      - bike-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - bike-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo
    networks:
      - bike-network

networks:
  bike-network:
    driver: bridge

volumes:
  postgres_data: